#!/bin/bash
# scripts/25-setup-zsh.sh
# Phase 2.5: Shell Configuration
# Installs Oh My Zsh, plugins, and ports user aliases/functions.

# Source libraries
LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/lib" && pwd)"
# Fallback if libs are missing (during dev)
if [[ -f "$LIB_DIR/logging.sh" ]]; then
    source "$LIB_DIR/logging.sh"
    source "$LIB_DIR/utils.sh"
else
    echo "Libraries not found, using simple fallback"
    log_header() { echo "=== $1 ==="; }
    log_info() { echo "[INFO] $1"; }
    log_success() { echo "[OK] $1"; }
    check_internet() { return 0; }
    ensure_directory() { mkdir -p "$1"; }
fi

log_header "Phase 2.5: Shell Configuration"

check_internet

ACTUAL_USER="${SUDO_USER:-$(whoami)}"
ACTUAL_HOME=$(eval echo "~$ACTUAL_USER")

#######################################
# 1. Install Oh My Zsh (Unattended)
#######################################
if [[ ! -d "$ACTUAL_HOME/.oh-my-zsh" ]]; then
    log_info "Installing Oh My Zsh..."
    if [[ "${DRY_RUN:-}" == "true" ]]; then
        log_info "[DRY RUN] Would clone Oh My Zsh"
    else
        # Run as user
        sudo -u "$ACTUAL_USER" sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    fi
else
    log_info "Oh My Zsh already installed"
fi

#######################################
# 2. Install Zsh Plugins
#######################################
ZSH_CUSTOM="$ACTUAL_HOME/.oh-my-zsh/custom"
PLUGINS_DIR="$ZSH_CUSTOM/plugins"

ensure_directory "$PLUGINS_DIR" "$ACTUAL_USER"

# Zsh Syntax Highlighting
if [[ ! -d "$PLUGINS_DIR/zsh-syntax-highlighting" ]]; then
    log_info "Installing zsh-syntax-highlighting..."
    if [[ "${DRY_RUN:-}" != "true" ]]; then
        sudo -u "$ACTUAL_USER" git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "$PLUGINS_DIR/zsh-syntax-highlighting"
    fi
else
    log_info "zsh-syntax-highlighting already installed"
fi

# Zsh Autosuggestions
if [[ ! -d "$PLUGINS_DIR/zsh-autosuggestions" ]]; then
    log_info "Installing zsh-autosuggestions..."
    if [[ "${DRY_RUN:-}" != "true" ]]; then
        sudo -u "$ACTUAL_USER" git clone https://github.com/zsh-users/zsh-autosuggestions "$PLUGINS_DIR/zsh-autosuggestions"
    fi
else
    log_info "zsh-autosuggestions already installed"
fi

#######################################
# 3. Inject User Configuration
#######################################
ZSHRC="$ACTUAL_HOME/.zshrc"
log_info "Configuring .zshrc..."

# Backup existing config
if [[ -f "$ZSHRC" ]]; then
    backup_file "$ZSHRC"
fi

# Write a CLEAN, safe .zshrc from scratch
# This fixes the "Desktop: command not found" loop error
cat > "$ZSHRC" <<EOF
# --- Generated by Fedora Dev Setup ---

# Path to Oh My Zsh
export ZSH="\$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="robbyrussell"

# Plugins (Added zoxide and thefuck here)
plugins=(git zsh-syntax-highlighting zsh-autosuggestions thefuck zoxide)

# Load Oh My Zsh
source \$ZSH/oh-my-zsh.sh

# --- User Configuration ---
export PATH="\$HOME/.local/bin:\$HOME/.cargo/bin:\$PATH"

# --- Tool Initialization ---
# Fixes: zoxide/thefuck command not found
if command -v zoxide &> /dev/null; then
    eval "\$(zoxide init zsh)"
    alias cd="z"
fi

if command -v thefuck &> /dev/null; then
    eval "\$(thefuck --alias)"
fi

if command -v direnv &> /dev/null; then
    eval "\$(direnv hook zsh)"
fi

# --- Custom Aliases ---
alias py='python3'
alias venv='python3 -m venv .venv && source .venv/bin/activate'
alias gc="git commit -m"
alias gp="git push origin HEAD"
alias gst="git status"

# --- Safe Custom Config Loading ---
# Only source files from a specific config directory, NEVER \$HOME/*
if [ -d "\$HOME/.config/zsh-custom" ]; then
    for config_file in "\$HOME/.config/zsh-custom/"*.zsh; do
        [ -f "\$config_file" ] && source "\$config_file"
    done
fi
EOF

# Ensure ownership is correct
chown "$ACTUAL_USER:$ACTUAL_USER" "$ZSHRC"

log_success "Shell configuration updated (Clean .zshrc generated)"